// flow-typed signature: 3a18f40a66c540020d4a967a12b362e3
// flow-typed version: <<STUB>>/webpack_v^3.4.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}
